---
- name: Deploy simple site on Windows client
  hosts: all
  gather_facts: no

  tasks:
    - name: Enable IIS
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole -All -NoRestart

    - name: Create site folder
      win_file:
        path: C:\simple_site
        state: directory

    - name: Copy site files
      win_copy:
        src: ./simple_site/
        dest: C:\simple_site\

    - name: Start IIS
      win_shell: |
        Start-Service W3SVC
