---
- name: Fully automated IIS site
  hosts: all
  gather_facts: no

  tasks:
    - name: Enable IIS
      win_shell: |
        Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebServerRole -All -NoRestart

    - name: Ensure IIS root exists
      win_file:
        path: C:\inetpub\wwwroot
        state: directory

    - name: Delete default IIS page
      win_file:
        path: C:\inetpub\wwwroot\iisstart.htm
        state: absent

    - name: Deploy my index.html
      win_copy:
        src: ./simple_site/index.html
        dest: C:\inetpub\wwwroot\index.html

    - name: Restart IIS
      win_shell: |
        Restart-Service W3SVC
