---
- name: Visible result demo
  hosts: all
  gather_facts: no

  tasks:
    - name: Create file on Desktop
      win_copy:
        content: "This was created by ansible"
        dest: C:\Users\kirth\Desktop\ansible\visible.txt
