---
- name: Visible result demo
  hosts: all
  gather_facts: no

  tasks:
    - name: Create file on Desktop
      win_copy:
        content: "This was created by AWX"
        dest: C:\Users\awxtest\Desktop\awx_visible.txt
